[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "T&E technical documentation"
authors = [{name = "Siméon Michel", email = "simeon.michel@vub.be"}]
dynamic = ["version", "description"]
